export const ADD_MYCLASS = "ADD_MYCLASS";
export const REMOVE_MYCLASS = "GET_MYCLASS";
export const SET_EXPLORE_CLASSES = "SET_EXPLORE_CLASSES";
export const SET_MYCLASSES = "SET_MYCLASSES";
export const SET_EXPLORE_CATEGORY = "SET_EXPLORE_CATEGORY";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CLASS = "SET_CLASS"
