
export const TEACHER_ADD_CLASS = "TEACHER_ADD_CLASS"
export const TEACHER_DELETE_CLASS = "TEACHER_DELETE_CLASS"
export const TEACHER_EDIT_CLASS = "TEACHER_EDIT_CLASS"
export const SET_CATEGORIES = "SET_CATEGORIES";