
export const TEACHER_ADD_CLASS = "TEACHER_ADD_CLASS";
export const TEACHER_DELETE_CLASS = "TEACHER_DELETE_CLASS";
export const TEACHER_EDIT_CLASS = "TEACHER_EDIT_CLASS";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const ADD_MYCLASS = "ADD_MYCLASS";
export const REMOVE_MYCLASS = "GET_MYCLASS";
export const SET_EXPLORE_CLASSES = "SET_EXPLORE_CLASSES";
export const SET_MYCLASSES = "SET_MYCLASSES";
export const SET_EXPLORE_CATEGORY = "SET_EXPLORE_CATEGORY";
export const SET_CLASS = "SET_CLASS";
export const SET_USER = "SET_USER";
export const UPDATE_PAYMENT = "UPDATE_PAYMENT";


